### PR TITLE
Better hardware support

### PR DESCRIPTION
**Pull request by persianpros**
After this we would experience more accuracy and better detection:
- Better VU+ detection
- Better 4K support (Various brands/models)
- lookuptable.txt kernel1.bin typo fixed
- Better xsarius detection
- Better GigaBlue detection (All models even 4Ks, lookuptable.txt should be updated too ...)
- Fix "hd51"/"h7" and use less python code for "sf4008"
- Faster checks and fix some kernel file detections
- Detect 4K "tar.bz2" extension
- Faster file detection for "jffs2" and "bin" extensions also support upcoming models with the reverse old models check

### CODE REVIEW

**Comment by Pedro-Newbie** [comment]
I sent you a mail on persianpros@yahoo.com, is this stil the right address?

**Comment by persianpros** [comment]
Yes my friend, I did answer it just now, You can merge this.

**Comment by Pedro-Newbie** [comment]
Merged the changes

**Comment by WanWizard** [comment]
And we merged too. 

Please note that on OpenPLi release images, all plugins are pinned on commit hash, which will only be updated if the new release introduced a fix for something broken for one of the boxes that release supports.

**Comment by persianpros** [comment]
@Pedro-Newbie you can remove this repo my friend.

**Comment by Pedro-Newbie** [comment]
I will, thanks for taking over the backupsuite, good luck

**Pull request merged**
